### PR TITLE
Contribute

### PR DESCRIPTION
**Pull request by Aim2339**
New command :sparkles:

### CODE REVIEW

**Comment by ZeroDiscord** [comment]
Appreciated, please see if you can include the drops feature aswell within the same PR id be happy to merge it in

**Comment by Aim2339** [comment]
> Appreciated, please see if you can include the drops feature aswell within the same PR id be happy to merge it in

Hi, actually can u tell me what exactly do ya mean by drops? Like a command or what?

**Comment by Aim2339** [comment]
And I also believe the drops feature is only possible in the normal prefix command? Anyways I'll sure include it in the same PR

**Comment by Aim2339** [comment]
Sure, I believe it's only possible in normal prefix command? If yes, then I'll commit it in the same PR.
Thanks!

**Comment by Aim2339** [comment]
> Sure, I believe it's only possible in normal prefix command? If yes, then I'll commit it in the same PR. Thanks!

facing issues with the drop command...

**Comment by Aim2339** [comment]
^^Here's something else

**Comment by ZeroDiscord** [comment]
Dont need ping part, please remove also you may contact me on discord if you are facing any issues while developing while I may be busy to write the whole command on my own ill be surely able to help you with your errors

**Pull request closed without merging**
