### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by ZeroDiscord** [comment]
Not needed

**Comment by Justman10000** [comment]
> Not needed

Fuck with me? Are we supposed to put up with your crappy copyright or what? Which is 0815 if everyone can see it? Then push your shit bot somewhere else, no more PRs from me!

**Comment by ZeroDiscord** [comment]
> Contributor

It can always be discussed, what is `0815` exactly?

**Comment by Justman10000** [comment]
> > Contributor
> 
> It can always be discussed, what is `0815` exactly? please with all due respect I never asked you to make PRs you did it on your own accord, so please watch the language.

Yes, just! I have invested my time and effort, what are you doing? Say, it is not needed, and closes the PR directly! Then you still say, we can discuss everything? Think about it first!

**Comment by Justman10000** [comment]
Then you wonder why I get angry? As I said, think first...

**Comment by ZeroDiscord** [comment]
> Then you wonder why I get angry? As I said, think first...

I understand you've worked hard although I don't understand why you'd propose this idea please give an explanation and what is `0812` exactly

**Comment by Justman10000** [comment]
> > Then you wonder why I get angry? As I said, think first...
> 
> I understand you've worked hard although I don't understand why you'd propose this idea please give an explanation

Can't you see in the commit? In addition, I had already mentioned it above, where you had my PR directly geschlosssen...

> ...what is `0815` exactly

As much as, garbage, extremely bad or useless for anything....

**Comment by Justman10000** [comment]
> > Then you wonder why I get angry? As I said, think first...
> 
> I understand you've worked hard although I don't understand why you'd propose this idea please give an explanation

Can't you see in the commit? In addition, I had already mentioned it above, where you had my PR directly closed...

> ...what is `0815` exactly

As much as, garbage, extremely bad or useless for anything....

**Comment by ZeroDiscord** [comment]
I don't see a reason as to why you should be able to select "your own copyright", could you please elaborate

**Comment by ZeroDiscord** [comment]
> > I don't see a reason as to why you should be able to select "your own copyright", could you please elaborate
> 
> Because it's 0815 and completely unprofessional for every pig to see the bot is from you...

Alright I understand your reasoning and I'm willing to merge this, but I am strictly warning you to mind your language as a contributor, this kind of language is not appreciated anywhere, especially my projects.

**Comment by Aim2339** [comment]
> > > I don't see a reason as to why you should be able to select "your own copyright", could you please elaborate
> > 
> > 
> > Because it's 0815 and completely unprofessional for every pig to see the bot is from you...
> 
> Alright I understand your reasoning and I'm willing to merge this, but I am strictly warning you to mind your language as a contributor, this kind of language is not appreciated anywhere, especially my projects.

Hey @Justman10000 man1000 I think you will have to define config in each file for it to work? ```config isn't defined```
Plus I was working on v14 now Im getting merge conflicts :sob:  [This](https://github.com/Aim2339/Giveaway/tree/djs-v14)

**Comment by ZeroDiscord** [comment]
> > > > I don't see a reason as to why you should be able to select "your own copyright", could you please elaborate
> > > 
> > > 
> > > Because it's 0815 and completely unprofessional for every pig to see the bot is from you...
> > 
> > Alright I understand your reasoning and I'm willing to merge this, but I am strictly warning you to mind your language as a contributor, this kind of language is not appreciated anywhere, especially my projects.
> 
> Hey @Justman10000 I think you will have to define config in each file for it to work? ```config isn't defined```
> Plus I was working on v14 now Im getting merge conflicts :sob:  [This](https://github.com/Aim2339/Giveaway/tree/djs-v14)

Please complete the PR while Justman works on the bug fix, I believe pulling it again after the fix would resolve the conflict.

**Comment by Aim2339** [comment]
> > > > > I don't see a reason as to why you should be able to select "your own copyright", could you please elaborate
> > > > 
> > > > 
> > > > Because it's 0815 and completely unprofessional for every pig to see the bot is from you...
> > > 
> > > 
> > > Alright I understand your reasoning and I'm willing to merge this, but I am strictly warning you to mind your language as a contributor, this kind of language is not appreciated anywhere, especially my projects.
> > 
> > 
> > Hey @Justman10000 I think you will have to define config in each file for it to work? `config isn't defined`
> > Plus I was working on v14 now Im getting merge conflicts sob  [This](https://github.com/Aim2339/Giveaway/tree/djs-v14)
> 
> Please complete the PR while Justman works on the bug fix, I believe pulling it again after the fix would resolve the conflict.

Yeah working on it

**Comment by Justman10000** [comment]
@Aim2339 @ZeroDiscord

I already do this...

**Comment by ZeroDiscord** [comment]
> @Aim2339 @ZeroDiscord
> 
> I already do this...

@Aim2339 please review

**Comment by Justman10000** [comment]
@ZeroDiscord @Aim2339

Is already declared

**Pull request merged**
